server:
  port: # 8080

spring:
  datasource:
    url: # e.g -> jdbc:postgresql://hostname:portNumber/databaseName
    username: # e.g -> postgres
    password: # e.g -> postgres_password
  jpa:
    hibernate:
      ddl-auto: # create-drop
      properties:
        hibernate: # org.hibernate.dialect.PostgreSQLDialect
        format_sql: # true
    show-sql: # true